using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraFollow : MonoBehaviour
{
    //Variables
    public Transform Target;
    [Header("Vectors")]
    //Velocidad seguimiento c치mara
    [SerializeField]
    private float _smoothing;
    //Distancia inicial entre c치mara y personaje
    [SerializeField]
    private Vector3 _offset;

    // Start is called before the first frame update
    void Start()
    {
        
        _offset = transform.position - Target.position;

    }

    private void LateUpdate()
    {

        //Posicion a la que queremos mover la c치mara
        Vector3 desiredPosition = Target.position + _offset;

        //Movemos la c치mara
        transform.position = Vector3.Lerp(transform.position, desiredPosition, _smoothing * Time.deltaTime);

    }

    
}
